name: Build

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
  schedule:
    - cron: '0 19 35 * *'
#  workflow_run:
#    workflows: ["Pylint+Flake8"]
#    types:
#      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=month::$(date +'%b')"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        chmod a+x get_json_hw_data_steam.py
    - name: "\"Build\" the JSON"
      run: |
        ./get_json_hw_data_steam.py
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: "${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}" #${{ steps.version.outputs.version }}
        tag_name: "${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}"
        body_path: /dev/null
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./steam_hw_survey_videocards.json
        asset_name: steam_hw_survey_videocards.json
        asset_content_type: application/json
